Controllers/HomeController.cs
using Cloud_Aissgnment_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;

namespace Cloud_Aissgnment_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<HomeController> _logger;


        // provate readonly IHttpContextAccessor _httpContextAccessor
        // int? userID = _httpCOntextAccessor.HttpContext.Seesion.GetInt32("UserID");
        public HomeController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _httpContextAccessor = httpContextAccessor; // Initialize IHttpContextAccessor
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Cart()
        {
            List<productTable> products = productTable.ReturnProducts();
            ViewData["products"] = products;
            return View();
        }

        public IActionResult Account()
        {
            int? test_userID = _httpContextAccessor.HttpContext.Session.GetInt32("UserID");

            if (null != test_userID)
            {
                int userID = (int) test_userID;
                
                //TempData["userID"] = userID;

                userTable usrtbl = new userTable();
                TransactionTable t = new TransactionTable();

                List<string> details = usrtbl.userDetails(userID);

                TempData["username"] = details[0];
                TempData["email"] = details[1];
                TempData["password"] = details[2];
                TempData["userID"] = userID;

                List<productTable> orders = t.getOrders(userID);
                List<productTable> products = t.getOwnedOrders(userID);
                TempData["orders"] = orders;
                TempData["products"] = products;
            }

            return View();
        }
        public IActionResult MyWorkPage()
        {
            List<productTable> products = productTable.ReturnProducts();
            ViewData["products"] = products;
            ViewData["userID"]  = _httpContextAccessor.HttpContext.Session.GetInt32("UserID");
            //Duplicate
            return View();
        }

        public IActionResult LoginSignup()
        {
            return View();
        }

        public IActionResult ErrorViewModel() { return View(); }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using Cloud_Aissgnment_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cloud_Aissgnment_1.Controllers
{
    public class ProductController : Controller
    {
        public productTable prdtbl = new productTable();
        public IActionResult ProductAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(productTable p)
        {
            // Receive data from the form
            var files = Request.Form.Files;
            var result = prdtbl.insertProduct(p);
            return RedirectToAction("MyWorkPage", "Home");
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [HttpPost]
        public ActionResult Cart(string userID, string productID)
        {
            TempData["productID"] = productID.ToString();
            TempData["userID"] = userID.ToString();
            return RedirectToAction("Cart", "Home", productID);
        }


    }
}

Controllers/TransactionController.cs
using Cloud_Aissgnment_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cloud_Aissgnment_1.Controllers
{
    public class TransactionController : Controller
    {
        TransactionTable t = new TransactionTable();
        [HttpPost]
        public ActionResult Buy(TransactionTable t2)
        {
            t.buyProduct(t2);
            TempData["productID"] = null;
            return RedirectToAction("MyWorkPage", "Home");
        }
        [HttpPost]
        public ActionResult ClearCart()
        {
            TempData["productID"] = null;
            return RedirectToAction("Cart", "Home");
        }
    }
}

Controllers/UserController.cs
using Cloud_Aissgnment_1.Models;
using Microsoft.AspNetCore.Mvc;


namespace Cloud_Aissgnment_1.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<HomeController> _logger;

        public UserController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _httpContextAccessor = httpContextAccessor; // Initialize IHttpContextAccessor
        }

        public userTable usrtbl = new userTable();
        public LoginModel lm = new LoginModel();

        [HttpPost]
        public ActionResult SignUp(userTable Users)
        {
            //Connected to about Page 
            var result = usrtbl.insertUser(Users);
            return RedirectToAction("About", "Home");
        }

        [HttpPost]
        public ActionResult Login(LoginModel l)
        {

            int UserID = lm.selectUser(l);
            if (UserID != -1)
            {
                // Redirect After User Found
                //TempData["userID"] = UserID;
                HttpContext.Session.SetInt32("UserID", UserID);
                return RedirectToAction("Account", "Home");
            }
            else
            {
                // User not found
                return Content("User Not Found", "text / html");
            }
        }


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Account()
        {
            if (TempData["userID"] != null)
            {

            }
            return RedirectToAction("Account", "Home");

        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="text-center">
<h1>About</h1>
<p id="blurb">James Khumalo, founder of KhumaloCraft Emporium, is passionate about connecting artisans with a global audience. 
    <br />He believes handcrafted products hold cultural significance and aims to build a thriving community around them. 
    <br />Prioritizing ethical sourcing and sustainability while empowering artisans with resources and a platform to share their stories.  </p>
</div>

Views/Home/Account.cshtml
@*
    For more information on enabling MVC for empty projects, visit (link unavailable)
*@
@{
    var userID = -1;
    var username = "";
    var email = "";
    var password = "";
    var orders = new List<Cloud_Aissgnment_1.Models.productTable> { };
    var products = new List<Cloud_Aissgnment_1.Models.productTable> { };

    if (TempData["userID"] != null)
    {
        userID = int.Parse(TempData["userID"].ToString());
        username = TempData["username"].ToString();
        email = TempData["email"].ToString();
        password = TempData["password"].ToString();

        orders = TempData["orders"] as List<Cloud_Aissgnment_1.Models.productTable>;
        products = TempData["products"] as List<Cloud_Aissgnment_1.Models.productTable>;
        TempData["userID"] = userID;
    }
    else
    {
        userID = -1;
    }

    // var orders = null;
    // var productsBought = null;
}

<div class="account-details">
    <h3>Account</h3>
    <p><strong>Username:</strong> @username</p>
    <p><strong>Email:</strong> @email</p>
    <strong>Password:</strong><input type="password" value="@password">
</div>

<h4>Client Orders</h4>

<div class="grid-container">
    @foreach (var p in products)
    {
        <div class="grid-item">
            <p class="grid-item-text">@p.Name</p>
            @* <img src=item.picture /> *@
            <p class="grid-item-text">R @p.Price</p>
        </div>
    }
</div>
<h4>Products Bought</h4>

<div class="grid-container">
@foreach (var o in orders)
{
    <div class="grid-item">
        <p class="grid-item-text">@o.Name</p>
       @*  <img src=item.picture /> *@
        <p class="grid-item-text">R @o.Price</p>
    </div>
}
</div>

Views/Home/Cart.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var products = ViewData["Products"] as List<Cloud_Aissgnment_1.Models.productTable>;
    int productID = -1;
    DateTime d = DateTime.Today;

    if (TempData["productID"] != null)
    {
        productID = int.Parse(@TempData["productID"].ToString());
        TempData["productID"] = productID;
    }



    var userID = -1;
    if (TempData["userID"] != null)
    {
        userID = int.Parse(TempData["userID"].ToString());
        TempData["userID"] = userID;
    }
    else
    {
        userID = -1;
    }
}

<h2>Ordered Product</h2>
<p> </p>
<p> </p>
@foreach (var item in products)
{
    if (item.ID == productID)
    {
        <div class="grid-item">
            <p class="grid-item-text">@item.Name</p>
            <img class="center img-block" src=@item.ImageSrcString />
            <p class="grid-item-text">R @item.Price</p>
        </div>
        if (@HttpContextAccessor.HttpContext.Session.GetInt32("UserID") != null)
        {
            <form class="form" asp-controller="Transaction" asp-action="Buy" method="post">
                @if (userID != null)
                {
                    <input type="hidden" name="userID" value="@userID" />
                    <input type="hidden" name="productID" value="@productID" />
                    <input type="hidden" name="date" value="@d" />
                    <input type="submit" value="Buy">
                }
            </form>
        }

    }

}
@if (TempData["productID"] == null)
{
    <p>Nothing to see here ...</p>
}
else
{

    <p></p>
    <form class="form" asp-controller="Transaction" asp-action="ClearCart" method="post">
        <input type="submit" value="Clear Cart" />
    </form>
}

Views/Home/ContactUs.cshtml
@model Cloud_Aissgnment_1.Models.userTable;


@{
    ViewData["Title"] = "Contact Us";
}

<div class="text-center">
    <h1 class="text-center" >@ViewData["Title"]</h1>

    <p id ="blurb">
        James Khumalo <br />
        Email: st10256074@vcconnect.edu.za <br />
        Phone: (+00) 000-000-0000
    </p>

</div>
<body>



</body>

Views/Home/Index.cshtml
@*James Hart ST10256074*@

@{
    ViewData["Title"] = "Home Page";
    // Fixes Bug where TempData survives restart and browser closure 
    // Issue : #30645
    TempData["userID"] = null;
    TempData["productID"] = null;

}


@*
    REF:
    https://www.pexels.com/photo/black-metal-scissors-803929/
    https://learn.microsoft.com/en-us/aspnet/core/?view=aspnetcore-8.0
    https://stackoverflow.com/questions/17838914/c-sharp-save-files-to-folder-on-server-instead-of-local
    https://stackoverflow.com/questions/12914473/how-can-i-show-up-openfiledialog-class-in-asp-net
    https://stackoverflow.com/questions/56528508/asp-net-core-tempdata-and-redirecttoaction-not-working
    https://stackoverflow.com/questions/527368/asp-net-mvc-multiple-controller-actions-in-one-form?rq=4
    https://stackoverflow.com/questions/2677072/asp-net-mvc-what-is-the-correct-way-to-redirect-to-pages-actions-in-mvc
*@

<img class="crop" src="~/img/pexels-eneida-nieves-803929.jpg" />

<div class="text-center">
    <h1  class="display-4">Welcome</h1>
    <p id="blurb">
        Discover unique, handcrafted treasures. <br />Shop exquisite goods made with love by skilled artisans around the world.  <br />Support artistry, elevate your life.<br />Find the perfect gift (or keep it for yourself)!
    </p>
</div>

Views/Home/LoginSignup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="form-container">
    <form class="form" asp-controller="User" asp-action="SignUp" method="post">
        <h2>Sign Up</h2>
        <input type="text" name="username" placeholder="Username" required>
        <input type="text" name="email" placeholder="Email" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="submit" value="Sign Up">
    </form>
    <form class="form" asp-controller="User" asp-action="Login" method="post">
        <h2>Login</h2>
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
</div>

Views/Home/MyWorkPage.cshtml
@* @Model int *@
@{
}
@{
    ViewData["Title"] = "Products";
    var userID = -1;
    if (ViewData["userID"] != null)
    {
        userID = int.Parse(ViewData["userID"].ToString());

    }
    var products = ViewData["Products"] as List<Cloud_Aissgnment_1.Models.productTable>;
}

<div class="product-center-block">
    <h1>Products </h1>
    @if (userID != -1)
    {
        <form asp-controller="Product" asp-action="ProductAdd" method="post">
            <input class="addProductButton" type="submit" value="Add Product">
        </form>
    }


    <div class="grid-container">
        @foreach (var item in products)
        {
            <form asp-controller="Product" asp-action="Cart" method="post" class="grid-item">

                <button class="product_button">
                    <p class="grid-item-text">@item.Name</p>
                    <img class="center img-block" src=@item.ImageSrcString />
                    <p class="grid-item-text">R @item.Price</p>
                    <p class="grid-item-text">Category: @item.Category</p>
                    <p class="grid-item-text">Instock: @item.Availability</p>
                    <input type="hidden" name="userID" value="@userID" />
                    <input type="hidden" name="productID" value="@item.ID" />
                    @* <input type="submit" value="Buy" /> *@
                </button>
            </form>

        }
    </div>
</div>